# Generated by Django 2.0 on 2020-11-15 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='answers_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
